import type { SectorConfig } from '../types';

export const sectors: SectorConfig[] = [
  {
    id: 'banking-financial-services',
    label: 'Banking & Financial Services',
    shortLabel: 'BFSI',
    description: 'Banks, NBFCs, payments, and broader financial intermediation in India.',
    theme: { primary: '#1D4ED8', soft: '#EFF6FF', border: '#BFDBFE' },
    keywords: ['RBI repo rate', 'NBFC lending', 'UPI transactions', 'public sector banks', 'NPA recovery', 'credit growth India', 'microfinance India', 'digital banking India'],
    excludeKeywords: ['US mortgage', 'crypto meme coin', 'European central bank', 'forex tourism'],
  },
  {
    id: 'insurance',
    label: 'Insurance',
    shortLabel: 'Insurance',
    description: 'Life, health, and general insurance developments in India.',
    theme: { primary: '#0F766E', soft: '#F0FDFA', border: '#99F6E4' },
    keywords: ['IRDAI circular', 'health insurance claims India', 'motor insurance premium', 'term insurance India', 'insurance penetration India', 'reinsurance India', 'policy surrender rules', 'bancassurance India'],
    excludeKeywords: ['US Medicare', 'pet insurance US', 'travel visa insurance', 'crypto insurance'],
  },
  {
    id: 'information-technology',
    label: 'Information Technology',
    shortLabel: 'IT',
    description: 'Indian IT services, software exports, and enterprise technology.',
    theme: { primary: '#7C3AED', soft: '#F5F3FF', border: '#DDD6FE' },
    keywords: ['IT services exports India', 'deal wins TCS Infosys', 'BFSI tech spending', 'GCC India hiring', 'rupee impact IT margins', 'AI services India', 'digital transformation contracts', 'Indian SaaS enterprise'],
    excludeKeywords: ['gaming laptop review', 'crypto mining rigs', 'social media influencers', 'US smartphone leaks'],
  },
  {
    id: 'telecom',
    label: 'Telecom',
    shortLabel: 'Telecom',
    description: 'Mobile networks, broadband, 5G rollout, and telecom policy in India.',
    theme: { primary: '#0284C7', soft: '#F0F9FF', border: '#BAE6FD' },
    keywords: ['5G rollout India', 'ARPU India telecom', 'BharatNet expansion', 'spectrum auction India', 'telecom tariff hike', 'fiber broadband India', 'DoT guidelines', 'satcom India licensing'],
    excludeKeywords: ['satellite phone hobby', 'US cable TV packages', 'mobile app reviews', 'consumer earbuds'],
  },
  {
    id: 'automobiles',
    label: 'Automobiles',
    shortLabel: 'Autos',
    description: 'Passenger vehicles, two-wheelers, commercial vehicles, and EV transition.',
    theme: { primary: '#DC2626', soft: '#FEF2F2', border: '#FECACA' },
    keywords: ['SIAM monthly dispatches', 'EV sales India', 'auto ancillaries India', 'vehicle scrappage policy', 'OEM production India', 'two-wheeler demand rural', 'battery swapping policy', 'commercial vehicle freight demand'],
    excludeKeywords: ['Formula 1 race recap', 'car modification tips', 'used car vlog', 'US pickup trucks'],
  },
  {
    id: 'pharmaceuticals',
    label: 'Pharmaceuticals',
    shortLabel: 'Pharma',
    description: 'Drug manufacturing, USFDA inspections, and Indian pharma exports.',
    theme: { primary: '#16A34A', soft: '#F0FDF4', border: '#BBF7D0' },
    keywords: ['USFDA warning letter India plant', 'API prices India', 'generic drug launches', 'PLI pharma India', 'CDMO India', 'drug pricing NPPA', 'biosimilars India', 'formulation exports India'],
    excludeKeywords: ['fitness supplement tips', 'cosmetic skincare routine', 'herbal home remedies', 'US pharmacy coupons'],
  },
  {
    id: 'healthcare-services',
    label: 'Healthcare Services',
    shortLabel: 'Healthcare',
    description: 'Hospitals, diagnostics, healthcare delivery, and care infrastructure.',
    theme: { primary: '#0EA5E9', soft: '#ECFEFF', border: '#A5F3FC' },
    keywords: ['hospital bed expansion India', 'diagnostics chain India', 'Ayushman Bharat reimbursement', 'medical tourism India', 'daycare surgery centers', 'healthcare occupancy rates', 'telemedicine India policy', 'NABH accreditation'],
    excludeKeywords: ['yoga classes', 'home workout plans', 'wellness retreats', 'vitamin blog'],
  },
  {
    id: 'fmcg',
    label: 'FMCG',
    shortLabel: 'FMCG',
    description: 'Packaged goods, staples, and daily-use consumer brands.',
    theme: { primary: '#EA580C', soft: '#FFF7ED', border: '#FED7AA' },
    keywords: ['rural demand FMCG India', 'commodity inflation soaps', 'HUL volume growth', 'distributor restocking India', 'packaged foods India', 'modern trade FMCG', 'price hikes staples India', 'personal care margins'],
    excludeKeywords: ['recipe blog', 'diet trends', 'restaurant reviews', 'beauty influencer'],
  },
  {
    id: 'consumer-durables',
    label: 'Consumer Durables',
    shortLabel: 'Durables',
    description: 'Appliances and durable household electronics demand trends.',
    theme: { primary: '#9333EA', soft: '#FAF5FF', border: '#E9D5FF' },
    keywords: ['air conditioner demand India', 'room AC inventory', 'PLI electronics India', 'appliance festive sales', 'import duty components', 'white goods India', 'cooling products demand', 'dealer channel stocking'],
    excludeKeywords: ['smartphone camera test', 'gaming console leaks', 'gadget unboxing', 'home decor ideas'],
  },
  {
    id: 'retail-e-commerce',
    label: 'Retail & E-Commerce',
    shortLabel: 'Retail',
    description: 'Organized retail chains and digital commerce in India.',
    theme: { primary: '#BE123C', soft: '#FFF1F2', border: '#FECDD3' },
    keywords: ['quick commerce India', 'festive season retail sales', 'mall footfall India', 'D2C brands India', 'e-commerce ONDC', 'inventory discounting India', 'retail leasing India', 'consumer sentiment urban India'],
    excludeKeywords: ['fashion haul', 'coupon codes', 'influencer storefront', 'US black friday deals'],
  },
  {
    id: 'real-estate',
    label: 'Real Estate',
    shortLabel: 'Real Estate',
    description: 'Residential, commercial, and regulatory trends across Indian realty.',
    theme: { primary: '#0369A1', soft: '#F0F9FF', border: '#BAE6FD' },
    keywords: ['RERA compliance', 'housing launches India', 'office leasing India', 'REIT distributions India', 'home loan rates India', 'affordable housing policy', 'unsold inventory India', 'metro city property demand'],
    excludeKeywords: ['interior design tips', 'vacation rentals', 'US housing starts', 'architecture awards'],
  },
  {
    id: 'cement',
    label: 'Cement',
    shortLabel: 'Cement',
    description: 'Cement demand, capacity additions, and pricing in India.',
    theme: { primary: '#78716C', soft: '#FAFAF9', border: '#E7E5E4' },
    keywords: ['cement price India', 'clinker capacity India', 'infrastructure cement demand', 'petcoke costs cement', 'rail freight cement', 'east region cement utilization', 'construction season demand', 'green cement India'],
    excludeKeywords: ['DIY concrete craft', 'home renovation hacks', 'global architecture fairs', 'US cement stocks'],
  },
  {
    id: 'metals-mining',
    label: 'Metals & Mining',
    shortLabel: 'Metals',
    description: 'Steel, non-ferrous metals, and mineral extraction in India.',
    theme: { primary: '#334155', soft: '#F8FAFC', border: '#CBD5E1' },
    keywords: ['steel demand India', 'iron ore auctions Odisha', 'coking coal imports', 'aluminium premiums India', 'mining lease renewal', 'metal export duty India', 'scrap prices India', 'NMDC production'],
    excludeKeywords: ['gold jewelry trends', 'crypto mining GPU', 'metal music festival', 'US steel jobs'],
  },
  {
    id: 'oil-gas',
    label: 'Oil & Gas',
    shortLabel: 'Oil & Gas',
    description: 'Upstream, refining, fuel retail, and gas infrastructure in India.',
    theme: { primary: '#B45309', soft: '#FFFBEB', border: '#FDE68A' },
    keywords: ['OMC marketing margins', 'crude basket India', 'city gas distribution', 'LNG imports India', 'windfall tax India', 'petrol diesel retail price', 'strategic petroleum reserve India', 'gas pipeline tariff PNGRB'],
    excludeKeywords: ['cooking gas stove review', 'US shale memes', 'car maintenance blog', 'crude oil trading tips'],
  },
  {
    id: 'power',
    label: 'Power',
    shortLabel: 'Power',
    description: 'Thermal and grid power demand, supply, and regulation.',
    theme: { primary: '#1E40AF', soft: '#EFF6FF', border: '#BFDBFE' },
    keywords: ['peak power demand India', 'coal stock at plants', 'DISCOM dues India', 'power exchange prices', 'electricity amendment bill', 'transmission projects India', 'AT&C loss reduction', 'merchant power tariffs'],
    excludeKeywords: ['portable generator reviews', 'solar lamp shopping', 'electric scooter tips', 'US powerball'],
  },
  {
    id: 'renewable-energy',
    label: 'Renewable Energy',
    shortLabel: 'Renewables',
    description: 'Solar, wind, storage, and green power policy in India.',
    theme: { primary: '#059669', soft: '#ECFDF5', border: '#A7F3D0' },
    keywords: ['solar module manufacturing India', 'SECI auction', 'wind capacity India', 'battery energy storage India', 'green hydrogen mission', 'open access renewable', 'renewable PPA tariffs', 'ALMM policy India'],
    excludeKeywords: ['home rooftop DIY', 'climate activism events', 'electric bike accessories', 'US solar rebates'],
  },
  {
    id: 'capital-goods-engineering',
    label: 'Capital Goods & Engineering',
    shortLabel: 'Cap Goods',
    description: 'Industrial equipment, machinery, and engineering order flows.',
    theme: { primary: '#0F766E', soft: '#F0FDFA', border: '#99F6E4' },
    keywords: ['order inflow engineering India', 'industrial capex cycle', 'defence manufacturing orders', 'rail electrification equipment', 'manufacturing PMI India', 'heavy electrical equipment', 'EPC margin trends', 'factory automation India'],
    excludeKeywords: ['DIY tools', 'consumer gadgets', 'US factory tours', 'mechanical tutorials'],
  },
  {
    id: 'infrastructure',
    label: 'Infrastructure',
    shortLabel: 'Infra',
    description: 'Roads, urban infrastructure, and public project execution.',
    theme: { primary: '#0369A1', soft: '#F0F9FF', border: '#BAE6FD' },
    keywords: ['NHAI project awards', 'HAM projects India', 'urban infra capex', 'smart city contracts', 'EPC road developers', 'construction equipment demand', 'project monetization TOT', 'state infra spending'],
    excludeKeywords: ['city travel guide', 'home improvement', 'US bridge collapse', 'architecture awards'],
  },
  {
    id: 'chemicals',
    label: 'Chemicals',
    shortLabel: 'Chemicals',
    description: 'Specialty, commodity, and agro-chemical manufacturing trends.',
    theme: { primary: '#7E22CE', soft: '#FAF5FF', border: '#E9D5FF' },
    keywords: ['specialty chemicals India', 'China plus one chemicals', 'caustic soda prices India', 'agrochemical exports India', 'fluorochemicals India', 'anti-dumping duty chemicals', 'input cost benzene India', 'chemical park India'],
    excludeKeywords: ['school chemistry experiments', 'beauty ingredients blog', 'pool cleaning tips', 'US lab research grants'],
  },
  {
    id: 'agriculture-fertilizers',
    label: 'Agriculture & Fertilizers',
    shortLabel: 'Agri',
    description: 'Farm inputs, fertilizer policy, and crop-linked demand.',
    theme: { primary: '#15803D', soft: '#F0FDF4', border: '#BBF7D0' },
    keywords: ['urea subsidy India', 'kharif sowing progress', 'DAP import India', 'fertilizer nutrient pricing', 'minimum support price', 'monsoon outlook India', 'agri input demand', 'soil health scheme India'],
    excludeKeywords: ['home gardening', 'organic recipes', 'US corn futures', 'farming simulator games'],
  },
  {
    id: 'textiles-apparel',
    label: 'Textiles & Apparel',
    shortLabel: 'Textiles',
    description: 'Yarn, fabrics, garment exports, and apparel consumption.',
    theme: { primary: '#BE185D', soft: '#FDF2F8', border: '#FBCFE8' },
    keywords: ['cotton prices India', 'MMF policy India', 'apparel exports India', 'technical textiles PLI', 'spinning margins India', 'garment unit expansion', 'EU demand for textiles', 'textile park PM MITRA'],
    excludeKeywords: ['fashion influencer reels', 'outfit ideas', 'wedding lehenga trends', 'US thrift shopping'],
  },
  {
    id: 'logistics',
    label: 'Logistics',
    shortLabel: 'Logistics',
    description: 'Freight movement, warehousing, and multimodal logistics.',
    theme: { primary: '#2563EB', soft: '#EFF6FF', border: '#BFDBFE' },
    keywords: ['GST e-way bill data', 'freight rates India', 'warehousing absorption India', 'multimodal logistics park', 'cold chain India', 'last-mile delivery costs', 'Gati Shakti projects', 'container availability India'],
    excludeKeywords: ['travel luggage reviews', 'shipping freebies', 'US trucking vlog', 'moving house tips'],
  },
  {
    id: 'aviation',
    label: 'Aviation',
    shortLabel: 'Aviation',
    description: 'Airlines, airports, fleet additions, and air traffic trends.',
    theme: { primary: '#1D4ED8', soft: '#EFF6FF', border: '#BFDBFE' },
    keywords: ['DGCA traffic data', 'domestic air passenger India', 'aircraft lease India', 'ATF prices India', 'airport privatization India', 'airline yield India', 'MRO policy India', 'regional connectivity UDAN'],
    excludeKeywords: ['vacation flight deals', 'pilot training vlog', 'airplane spotting', 'US TSA rules'],
  },
  {
    id: 'hospitality',
    label: 'Hospitality',
    shortLabel: 'Hospitality',
    description: 'Hotels, travel stays, and occupancy-revenue trends.',
    theme: { primary: '#0EA5A4', soft: '#F0FDFA', border: '#99F6E4' },
    keywords: ['hotel occupancy India', 'RevPAR India hotels', 'business travel India', 'religious tourism demand', 'room supply additions', 'hospitality tax policy India', 'luxury hotel pipeline', 'online travel agency India'],
    excludeKeywords: ['food recipes', 'travel vlogs', 'home stays reviews', 'US cruise holidays'],
  },
  {
    id: 'media-entertainment',
    label: 'Media & Entertainment',
    shortLabel: 'Media',
    description: 'Broadcasting, digital media, and entertainment monetization.',
    theme: { primary: '#7C2D12', soft: '#FFF7ED', border: '#FDBA74' },
    keywords: ['TRAI broadcasting tariff', 'OTT subscription India', 'ad revenue TV India', 'box office India', 'sports rights bidding', 'music streaming India', 'digital ad spend India', 'media merger India'],
    excludeKeywords: ['movie spoilers', 'celebrity gossip', 'fan edits', 'US reality shows'],
  },
  {
    id: 'defence-aerospace',
    label: 'Defence & Aerospace',
    shortLabel: 'Defence',
    description: 'Defence procurement, aerospace manufacturing, and offsets.',
    theme: { primary: '#1F2937', soft: '#F9FAFB', border: '#D1D5DB' },
    keywords: ['defence procurement India', 'Make in India defence', 'HAL order book', 'DRDO program update', 'offset policy India', 'defence export India', 'military aviation India', 'naval shipbuilding India'],
    excludeKeywords: ['war video games', 'history documentaries', 'airshow hobby', 'US military politics'],
  },
  {
    id: 'railways',
    label: 'Railways',
    shortLabel: 'Railways',
    description: 'Rail infrastructure, rolling stock, and passenger-freight operations.',
    theme: { primary: '#075985', soft: '#F0F9FF', border: '#BAE6FD' },
    keywords: ['Indian Railways capex', 'Vande Bharat rollout', 'rail freight loading', 'station redevelopment India', 'Kavach deployment', 'wagon demand India', 'railway electrification pace', 'DFCCIL progress'],
    excludeKeywords: ['train travel vlog', 'rail fan photos', 'model trains', 'US subway maps'],
  },
  {
    id: 'ports-shipping',
    label: 'Ports & Shipping',
    shortLabel: 'Ports',
    description: 'Port cargo, shipping lines, and maritime infrastructure.',
    theme: { primary: '#0C4A6E', soft: '#F0F9FF', border: '#BAE6FD' },
    keywords: ['major ports cargo India', 'container throughput JNPT', 'coastal shipping India', 'shipbuilding India', 'Sagarmala projects', 'freight corridor ports', 'charter rates India', 'maritime policy India'],
    excludeKeywords: ['cruise vacation tips', 'fishing hobby', 'yacht lifestyle', 'US harbor tourism'],
  },
  {
    id: 'semiconductors-electronics-manufacturing',
    label: 'Semiconductors & Electronics Manufacturing',
    shortLabel: 'Semiconductors',
    description: 'Chip ecosystem and electronics manufacturing expansion in India.',
    theme: { primary: '#4F46E5', soft: '#EEF2FF', border: '#C7D2FE' },
    keywords: ['India semiconductor mission', 'OSAT India', 'electronics PLI scheme', 'display fab India', 'chip packaging India', 'mobile manufacturing India', 'component localization India', 'supply chain resilience India'],
    excludeKeywords: ['PC hardware reviews', 'gaming GPU benchmarks', 'crypto mining chips', 'US tech leaks'],
  },
];
